remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Central Illinois Bombers Softball
description: Central Illinois Bombers Softball

collections:
  players:
    output: true
    permalink: /players/:name/
